pub struct Activity {}
pub struct IntransitiveActivity {}

pub struct Accept {}
pub struct Add {}
pub struct Announce {}
pub struct Arrive {}
pub struct Block {}
pub struct Create {}
pub struct Delete {}
pub struct Dislike {}
pub struct Flag {}
pub struct Follow {}
pub struct Ignore {}
pub struct Invite {}
pub struct Join {}
pub struct Leave {}
pub struct Like {}
pub struct Listen {}
pub struct Move {}
pub struct Offer {}
pub struct Question {}
pub struct Read {}
pub struct Reject {}
pub struct Remove {}
pub struct TentativeAccept {}
pub struct TentativeReject {}
pub struct Travel {}
pub struct Undo {}
pub struct Update {}
pub struct View {}
